In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import optuna
from optuna_integration import OptunaSearchCV
from scikeras.wrappers import KerasClassifier

In [2]:
# All the data processing, preprocessing activities are similar to Machine Learning Models

In [3]:
# Standardization - ANN -- Help the neural to process the compute fast
# Function will converge fast

In [4]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\sneha\anaconda assignment\excel\Churn_Modelling.csv')

In [5]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
dataset_new = dataset.drop(columns = ['Geography', 'RowNumber', 'CustomerId','Surname','Gender'])

In [7]:
dataset_new

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0
9996,516,35,10,57369.61,1,1,1,101699.77,0
9997,709,36,7,0.00,1,0,1,42085.58,1
9998,772,42,3,75075.31,2,1,0,92888.52,1
9999,792,28,4,130142.79,1,1,0,38190.78,0

In [8]:
X = dataset_new.iloc[:, 0:10].values
y = dataset_new.Exited.values

In [9]:
X

array([[6.1900000e+02, 4.2000000e+01, 2.0000000e+00, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [6.0800000e+02, 4.1000000e+01, 1.0000000e+00, ..., 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00],
       [5.0200000e+02, 4.2000000e+01, 8.0000000e+00, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [7.0900000e+02, 3.6000000e+01, 7.0000000e+00, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [7.7200000e+02, 4.2000000e+01, 3.0000000e+00, ..., 0.0000000e+00,
        9.2888520e+04, 1.0000000e+00],
       [7.9200000e+02, 2.8000000e+01, 4.0000000e+00, ..., 0.0000000e+00,
        3.8190780e+04, 0.0000000e+00]], shape=(10000, 9))

In [10]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
# Feature Scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
# Modelling phase

In [13]:
Dense?

Init signature:
Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    lora_rank=None,
    lora_alpha=None,
    quantization_config=None,
    **kwargs,
)
Docstring:
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). When this layer is
followed by a `BatchNormalization` layer, it is recommended to set
`use_bias=False` as `BatchNormalization` has its own bias term.

Note: If the input to the layer has a rank greater than 2, `Dense`
computes the dot product between the `inputs` and the `kernel` along the
last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
For example, if input has dimensions `(batch_size, d0, d1)`, then we create
a `kernel` with shape `(d1, units)`, and the `kernel` operates along axis 2
of the `input`, on every sub-tensor of shape `(1, 1, d1)` (there are
`batch_size * d0` such sub-tensors). The output in this case will have
shape `(batch_size, d0, units)`.

Args:
    units: Positive integer, dimensionality of the output space.
    activation: Activation function to use.
        If you don't specify anything, no activation is applied
        (ie. "linear" activation: `a(x) = x`).
    use_bias: Boolean, whether the layer uses a bias vector.
    kernel_initializer: Initializer for the `kernel` weights matrix.
    bias_initializer: Initializer for the bias vector.
    kernel_regularizer: Regularizer function applied to
        the `kernel` weights matrix.
    bias_regularizer: Regularizer function applied to the bias vector.
    activity_regularizer: Regularizer function applied to
        the output of the layer (its "activation").
    kernel_constraint: Constraint function applied to
        the `kernel` weights matrix.
    bias_constraint: Constraint function applied to the bias vector.
    lora_rank: Optional integer. If set, the layer's forward pass
        will implement LoRA (Low-Rank Adaptation)
        with the provided rank. LoRA sets the layer's kernel
        to non-trainable and replaces it with a delta over the
        original kernel, obtained via multiplying two lower-rank
        trainable matrices. This can be useful to reduce the
        computation cost of fine-tuning large dense layers.
        You can also enable LoRA on an existing
        `Dense` layer by calling `layer.enable_lora(rank)`.
    lora_alpha: Optional integer. If set, this parameter scales the
        low-rank adaptation delta (computed as the product of two lower-rank
        trainable matrices) during the forward pass. The delta is scaled by
        `lora_alpha / lora_rank`, allowing you to fine-tune the strength of
        the LoRA adjustment independently of `lora_rank`.

Input shape:
    N-D tensor with shape: `(batch_size, ..., input_dim)`.
    The most common situation would be
    a 2D input with shape `(batch_size, input_dim)`.

Output shape:
    N-D tensor with shape: `(batch_size, ..., units)`.
    For instance, for a 2D input with shape `(batch_size, input_dim)`,
    the output would have shape `(batch_size, units)`.
File:           c:\users\sneha\anaconda3\lib\site-packages\keras\src\layers\core\dense.py
Type:           type
Subclasses:

In [14]:
#[9,6,6,1]  =
# Setting up the Networks
#Initializing Neural Network
classifier = Sequential()   #Feed forward neural networks

classifier.add(Dense(units = 6, activation = 'relu', input_dim = 9))  # First Hidden Layer
classifier.add(Dense(units = 6, activation = 'relu'))
classifier.add(Dense(units = 1, activation = 'sigmoid'))

C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
# adam, adamW, GradientDescent  - Hyperparamter
# loss function
# metrics - accuracy, F1 score

In [16]:
classifier.compile?

Signature:
classifier.compile(
    optimizer='rmsprop',
    loss=None,
    loss_weights=None,
    metrics=None,
    weighted_metrics=None,
    run_eagerly=False,
    steps_per_execution=1,
    jit_compile='auto',
    auto_scale_loss=True,
)
Docstring:
Configures the model for training.

Example:

```python
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=[
        keras.metrics.BinaryAccuracy(),
        keras.metrics.FalseNegatives(),
    ],
)
```

Args:
    optimizer: String (name of optimizer) or optimizer instance. See
        `keras.optimizers`.
    loss: Loss function. May be a string (name of loss function), or
        a `keras.losses.Loss` instance. See `keras.losses`. A
        loss function is any callable with the signature
        `loss = fn(y_true, y_pred)`, where `y_true` are the ground truth
        values, and `y_pred` are the model's predictions.
        `y_true` should have shape `(batch_size, d0, .. dN)`
        (except in the case of sparse loss functions such as
        sparse categorical crossentropy which expects integer arrays of
        shape `(batch_size, d0, .. dN-1)`).
        `y_pred` should have shape `(batch_size, d0, .. dN)`.
        The loss function should return a float tensor.
    loss_weights: Optional list or dictionary specifying scalar
        coefficients (Python floats) to weight the loss contributions of
        different model outputs. The loss value that will be minimized
        by the model will then be the *weighted sum* of all individual
        losses, weighted by the `loss_weights` coefficients.  If a list,
        it is expected to have a 1:1 mapping to the model's outputs. If
        a dict, it is expected to map output names (strings) to scalar
        coefficients.
    metrics: List of metrics to be evaluated by the model during
        training and testing. Each of this can be a string (name of a
        built-in function), function or a `keras.metrics.Metric`
        instance. See `keras.metrics`. Typically you will use
        `metrics=['accuracy']`. A function is any callable with the
        signature `result = fn(y_true, _pred)`. To specify different
        metrics for different outputs of a multi-output model, you could
        also pass a dictionary, such as
        `metrics={'a':'accuracy', 'b':['accuracy', 'mse']}`.
        You can also pass a list to specify a metric or a list of
        metrics for each output, such as
        `metrics=[['accuracy'], ['accuracy', 'mse']]`
        or `metrics=['accuracy', ['accuracy', 'mse']]`. When you pass
        the strings 'accuracy' or 'acc', we convert this to one of
        `keras.metrics.BinaryAccuracy`,
        `keras.metrics.CategoricalAccuracy`,
        `keras.metrics.SparseCategoricalAccuracy` based on the
        shapes of the targets and of the model output. A similar
        conversion is done for the strings `"crossentropy"`
        and `"ce"` as well.
        The metrics passed here are evaluated without sample weighting;
        if you would like sample weighting to apply, you can specify
        your metrics via the `weighted_metrics` argument instead.
    weighted_metrics: List of metrics to be evaluated and weighted by
        `sample_weight` or `class_weight` during training and testing.
    run_eagerly: Bool. If `True`, this model's forward pass
         will never be compiled. It is recommended to leave this
         as `False` when training (for best performance),
         and to set it to `True` when debugging.
    steps_per_execution: Int. The number of batches to run
        during each a single compiled function call. Running multiple
        batches inside a single compiled function call can
        greatly improve performance on TPUs or small models with a large
        Python overhead. At most, one full epoch will be run each
        execution. If a number larger than the size of the epoch is
        passed, the execution will be truncated to the size of the
        epoch. Note that if `steps_per_execution` is set to `N`,
        `Callback.on_batch_begin` and `Callback.on_batch_end` methods
        will only be called every `N` batches (i.e. before/after
        each compiled function execution).
        Not supported with the PyTorch backend.
    jit_compile: Bool or `"auto"`. Whether to use XLA compilation when
        compiling a model. For `jax` and `tensorflow` backends,
        `jit_compile="auto"` enables XLA compilation if the model
        supports it, and disabled otherwise.
        For `torch` backend, `"auto"` will default to eager
        execution and `jit_compile=True` will run with `torch.compile`
        with the `"inductor"` backend.
    auto_scale_loss: Bool. If `True` and the model dtype policy is
        `"mixed_float16"`, the passed optimizer will be automatically
        wrapped in a `LossScaleOptimizer`, which will dynamically
        scale the loss to prevent underflow.

Note:
    Trainable variables are determined at `compile()` time. If you
    modify the `trainable` property of a layer after calling
    `compile()`, those changes will not take effect during `fit()`
    unless `compile()` is called again.

    Recommended workflow when changing trainable variables:
    ```python
    # Initial training with some layers
    model.compile(optimizer="adam", loss="mse")
    model.fit(x_train, y_train)

    # Change trainable flags
    layer.trainable = False  # or True

    # Recompile for the change to take effect
    model.compile(optimizer="adam", loss="mse")
    model.fit(x_train, y_train)
    ```

    This behavior applies to all Keras backends and is also documented
    in the transfer learning guide.
File:      c:\users\sneha\anaconda3\lib\site-packages\keras\src\trainers\trainer.py
Type:      method

In [17]:
# Compiling Neural Network - Setting up Loss and Optimizers
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [18]:
# in one round how may records should pass for training
# 500, 20 iterations

In [19]:
classifier.fit?

Signature:
classifier.fit(
    x=None,
    y=None,
    batch_size=None,
    epochs=1,
    verbose='auto',
    callbacks=None,
    validation_split=0.0,
    validation_data=None,
    shuffle=True,
    class_weight=None,
    sample_weight=None,
    initial_epoch=0,
    steps_per_epoch=None,
    validation_steps=None,
    validation_batch_size=None,
    validation_freq=1,
)
Docstring:
Trains the model for a fixed number of epochs (dataset iterations).

Args:
    x: Input data. It can be:
        - A NumPy array (or array-like), or a list of arrays
        (in case the model has multiple inputs).
        - A backend-native tensor, or a list of tensors
        (in case the model has multiple inputs).
        - A dict mapping input names to the corresponding array/tensors,
        if the model has named inputs.
        - A `keras.utils.PyDataset` returning `(inputs, targets)` or
        `(inputs, targets, sample_weights)`.
        - A `tf.data.Dataset` yielding `(inputs, targets)` or
        `(inputs, targets, sample_weights)`.
        - A `torch.utils.data.DataLoader` yielding `(inputs, targets)`
        or `(inputs, targets, sample_weights)`.
        - A Python generator function yielding `(inputs, targets)` or
        `(inputs, targets, sample_weights)`.
    y: Target data. Like the input data `x`, it can be either NumPy
        array(s) or backend-native tensor(s). If `x` is a
        `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or a Python generator function,
        `y` should not be specified since targets will be obtained from
        `x`.
    batch_size: Integer or `None`.
        Number of samples per gradient update.
        If unspecified, `batch_size` will default to 32.
        Do not specify the `batch_size` if your input data `x` is a
        `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or Python generator function
        since they generate batches.
    epochs: Integer. Number of epochs to train the model.
        An epoch is an iteration over the entire `x` and `y`
        data provided
        (unless the `steps_per_epoch` flag is set to
        something other than None).
        Note that in conjunction with `initial_epoch`,
        `epochs` is to be understood as "final epoch".
        The model is not trained for a number of iterations
        given by `epochs`, but merely until the epoch
        of index `epochs` is reached.
    verbose: `"auto"`, 0, 1, or 2. Verbosity mode.
        0 = silent, 1 = progress bar, 2 = one line per epoch.
        "auto" becomes 1 for most cases.
        Note that the progress bar is not
        particularly useful when logged to a file,
        so `verbose=2` is recommended when not running interactively
        (e.g., in a production environment). Defaults to `"auto"`.
    callbacks: List of `keras.callbacks.Callback` instances.
        List of callbacks to apply during training.
        See `keras.callbacks`. Note
        `keras.callbacks.ProgbarLogger` and
        `keras.callbacks.History` callbacks are created
        automatically and need not be passed to `model.fit()`.
        `keras.callbacks.ProgbarLogger` is created
        or not based on the `verbose` argument in `model.fit()`.
    validation_split: Float between 0 and 1.
        Fraction of the training data to be used as validation data.
        The model will set apart this fraction of the training data,
        will not train on it, and will evaluate the loss and any model
        metrics on this data at the end of each epoch. The validation
        data is selected from the last samples in the `x` and `y` data
        provided, before shuffling.
        This argument is only supported when `x` and `y` are made of
        NumPy arrays or tensors.
        If both `validation_data` and `validation_split` are provided,
        `validation_data` will override `validation_split`.
    validation_data: Data on which to evaluate
        the loss and any model metrics at the end of each epoch.
        The model will not be trained on this data. Thus, note the fact
        that the validation loss of data provided using
        `validation_split` or `validation_data` is not affected by
        regularization layers like noise and dropout.
        `validation_data` will override `validation_split`.
        It can be:
        - A tuple `(x_val, y_val)` of NumPy arrays or tensors.
        - A tuple `(x_val, y_val, val_sample_weights)` of NumPy
        arrays.
        - A `keras.utils.PyDataset`, a `tf.data.Dataset`, a
        `torch.utils.data.DataLoader` yielding `(inputs, targets)` or a
        Python generator function yielding `(x_val, y_val)` or
        `(inputs, targets, sample_weights)`.
    shuffle: Boolean, whether to shuffle the training data before each
        epoch. This argument is ignored when `x` is a
        `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or Python generator function.
    class_weight: Optional dictionary mapping class indices (integers)
        to a weight (float) value, used for weighting the loss function
        (during training only).
        This can be useful to tell the model to
        "pay more attention" to samples from
        an under-represented class. When `class_weight` is specified
        and targets have a rank of 2 or greater, either `y` must be
        one-hot encoded, or an explicit final dimension of `1` must
        be included for sparse class labels.
    sample_weight: Optional NumPy array or tensor of weights for
        the training samples, used for weighting the loss function
        (during training only). You can either pass a flat (1D)
        NumPy array or tensor with the same length as the input samples
        (1:1 mapping between weights and samples), or in the case of
        temporal data, you can pass a 2D NumPy array or tensor with
        shape `(samples, sequence_length)` to apply a different weight
        to every timestep of every sample.
        This argument is not supported when `x` is a
        `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or Python generator function.
        Instead, provide `sample_weights` as the third element of `x`.
        Note that sample weighting does not apply to metrics specified
        via the `metrics` argument in `compile()`. To apply sample
        weighting to your metrics, you can specify them via the
        `weighted_metrics` in `compile()` instead.
    initial_epoch: Integer.
        Epoch at which to start training
        (useful for resuming a previous training run).
    steps_per_epoch: Integer or `None`.
        Total number of steps (batches of samples) before declaring one
        epoch finished and starting the next epoch. When training with
        input tensors or NumPy arrays, the default `None` means that the
        value used is the number of samples in your dataset divided by
        the batch size, or 1 if that cannot be determined.
        If `x` is a `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or Python generator function, the
        epoch will run until the input dataset is exhausted. When
        passing an infinitely repeating dataset, you must specify the
        `steps_per_epoch` argument, otherwise the training will run
        indefinitely.
    validation_steps: Integer or `None`.
        Only relevant if `validation_data` is provided.
        Total number of steps (batches of samples) to draw before
        stopping when performing validation at the end of every epoch.
        If `validation_steps` is `None`, validation will run until the
        `validation_data` dataset is exhausted. In the case of an
        infinitely repeating dataset, it will run indefinitely. If
        `validation_steps` is specified and only part of the dataset
        is consumed, the evaluation will start from the beginning of the
        dataset at each epoch. This ensures that the same validation
        samples are used every time.
    validation_batch_size: Integer or `None`.
        Number of samples per validation batch.
        If unspecified, will default to `batch_size`.
        Do not specify the `validation_batch_size` if your data is a
        `keras.utils.PyDataset`, `tf.data.Dataset`,
        `torch.utils.data.DataLoader` or Python generator function
        since they generate batches.
    validation_freq: Only relevant if validation data is provided.
        Specifies how many training epochs to run
        before a new validation run is performed,
        e.g. `validation_freq=2` runs validation every 2 epochs.

Unpacking behavior for iterator-like inputs:
    A common pattern is to pass an iterator like object such as a
    `tf.data.Dataset` or a `keras.utils.PyDataset` to `fit()`,
    which will in fact yield not only features (`x`)
    but optionally targets (`y`) and sample weights (`sample_weight`).
    Keras requires that the output of such iterator-likes be
    unambiguous. The iterator should return a tuple
    of length 1, 2, or 3, where the optional second and third elements
    will be used for `y` and `sample_weight` respectively.
    Any other type provided will be wrapped in
    a length-one tuple, effectively treating everything as `x`. When
    yielding dicts, they should still adhere to the top-level tuple
    structure,
    e.g. `({"x0": x0, "x1": x1}, y)`. Keras will not attempt to separate
    features, targets, and weights from the keys of a single dict.
    A notable unsupported data type is the `namedtuple`. The reason is
    that it behaves like both an ordered datatype (tuple) and a mapping
    datatype (dict). So given a namedtuple of the form:
    `namedtuple("example_tuple", ["y", "x"])`
    it is ambiguous whether to reverse the order of the elements when
    interpreting the value. Even worse is a tuple of the form:
    `namedtuple("other_tuple", ["x", "y", "z"])`
    where it is unclear if the tuple was intended to be unpacked
    into `x`, `y`, and `sample_weight` or passed through
    as a single element to `x`.

Returns:
    A `History` object. Its `History.history` attribute is
    a record of training loss values and metrics values
    at successive epochs, as well as validation loss values
    and validation metrics values (if applicable).
File:      c:\users\sneha\anaconda3\lib\site-packages\keras\src\backend\tensorflow\trainer.py
Type:      method

In [20]:
# Fitting our model - Training
classifier.fit(X_train, y_train, batch_size = 500, epochs = 20, validation_data=[X_test, y_test])

Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.3848 - loss: 1.0186 - val_accuracy: 0.4395 - val_loss: 0.9150
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5110 - loss: 0.8308 - val_accuracy: 0.5460 - val_loss: 0.7665
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6071 - loss: 0.7098 - val_accuracy: 0.6500 - val_loss: 0.6667
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6896 - loss: 0.6258 - val_accuracy: 0.7235 - val_loss: 0.5950
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7600 - loss: 0.5635 - val_accuracy: 0.7870 - val_loss: 0.5402
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8198 - loss: 0.5146 - val_accuracy: 0.8380 - val_loss: 0.4958
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8635 - loss: 0.4742 - val_accuracy: 0.8795 - val_loss: 0.4582
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8944 - loss: 0.4392 - val_accuracy: 0.9080 - val_loss: 0.4249
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9197 - loss: 0.4077 - val_accuracy: 0.9225 - val_loss: 0.3948
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9388 - loss: 0.3792 - val_accuracy: 0.9345 - val_loss: 0.3672
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9504 - loss: 0.3529 - val_accuracy: 0.9515 - val_loss: 0.3416
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9606 - loss: 0.3284 - val_accuracy: 0.9625 - val_loss: 0.3178
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9690 - loss: 0.3054 - val_accuracy: 0.9695 - val_loss: 0.2954
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9770 - loss: 0.2839 - val_accuracy: 0.9770 - val_loss: 0.2745
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9840 - loss: 0.2637 - val_accuracy: 0.9850 - val_loss: 0.2550
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9896 - loss: 0.2449 - val_accuracy: 0.9910 - val_loss: 0.2368
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9929 - loss: 0.2274 - val_accuracy: 0.9950 - val_loss: 0.2199
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9955 - loss: 0.2112 - val_accuracy: 0.9965 - val_loss: 0.2044
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9967 - loss: 0.1963 - val_accuracy: 0.9970 - val_loss: 0.1901
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9979 - loss: 0.1827 - val_accuracy: 0.9970 - val_loss: 0.1770

In [21]:
# Parameters eligible for tuning
# Layers
# Neurons
# activation function
# optimizer
# batch_size
# epoch

In [22]:
# Predicting the Test set results # prediction
y_pred = classifier.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [23]:
y_pred

array([[0.14339134],
       [0.01178862],
       [0.1288762 ],
       ...,
       [0.16156034],
       [0.24672   ],
       [0.18248221]], shape=(2000, 1), dtype=float32)

In [24]:
y_test

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [25]:
y_pred = (y_pred > 0.5)

In [26]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], shape=(2000, 1))

In [27]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [28]:
cm

array([[1598,    0],
       [   6,  396]])

In [29]:
X

array([[6.1900000e+02, 4.2000000e+01, 2.0000000e+00, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [6.0800000e+02, 4.1000000e+01, 1.0000000e+00, ..., 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00],
       [5.0200000e+02, 4.2000000e+01, 8.0000000e+00, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [7.0900000e+02, 3.6000000e+01, 7.0000000e+00, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [7.7200000e+02, 4.2000000e+01, 3.0000000e+00, ..., 0.0000000e+00,
        9.2888520e+04, 1.0000000e+00],
       [7.9200000e+02, 2.8000000e+01, 4.0000000e+00, ..., 0.0000000e+00,
        3.8190780e+04, 0.0000000e+00]], shape=(10000, 9))

In [30]:
# Predicting the Test set results
y_pred_train = classifier.predict(X_train)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [31]:
y_pred_train = (y_pred_train > 0.5)

In [32]:
import sklearn.metrics as metrics
print(metrics.classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6365
           1       1.00      0.99      1.00      1635

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000

In [33]:
import sklearn.metrics as metrics
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1598
           1       1.00      0.99      0.99       402

    accuracy                           1.00      2000
   macro avg       1.00      0.99      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [34]:
# 91% of F1 score

In [35]:
# Parameters eligible for tuning
# Layers
# Neurons
# activation function
# optimizer
# batch_size
# epoch

In [36]:
GridsearchCV
# Methods for ANN HyperparamterTuning
# Two popular packages

# Optuna - Image Classification projects - Very Popular
# RayTune
# HyperOpt

NameError: name 'GridsearchCV' is not defined

In [ ]:
# tag Optuna - Documentation

In [ ]:
import optuna
from optuna_integration import OptunaSearchCV

In [ ]:
#https://optuna.org/

In [ ]:
OptunaSearchCV?

In [ ]:
# Compiling Neural Network - Setting up Loss and Optimizers
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [37]:
classifier.compile?

Signature:
classifier.compile(
    optimizer='rmsprop',
    loss=None,
    loss_weights=None,
    metrics=None,
    weighted_metrics=None,
    run_eagerly=False,
    steps_per_execution=1,
    jit_compile='auto',
    auto_scale_loss=True,
)
Docstring:
Configures the model for training.

Example:

```python
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=[
        keras.metrics.BinaryAccuracy(),
        keras.metrics.FalseNegatives(),
    ],
)
```

Args:
    optimizer: String (name of optimizer) or optimizer instance. See
        `keras.optimizers`.
    loss: Loss function. May be a string (name of loss function), or
        a `keras.losses.Loss` instance. See `keras.losses`. A
        loss function is any callable with the signature
        `loss = fn(y_true, y_pred)`, where `y_true` are the ground truth
        values, and `y_pred` are the model's predictions.
        `y_true` should have shape `(batch_size, d0, .. dN)`
        (except in the case of sparse loss functions such as
        sparse categorical crossentropy which expects integer arrays of
        shape `(batch_size, d0, .. dN-1)`).
        `y_pred` should have shape `(batch_size, d0, .. dN)`.
        The loss function should return a float tensor.
    loss_weights: Optional list or dictionary specifying scalar
        coefficients (Python floats) to weight the loss contributions of
        different model outputs. The loss value that will be minimized
        by the model will then be the *weighted sum* of all individual
        losses, weighted by the `loss_weights` coefficients.  If a list,
        it is expected to have a 1:1 mapping to the model's outputs. If
        a dict, it is expected to map output names (strings) to scalar
        coefficients.
    metrics: List of metrics to be evaluated by the model during
        training and testing. Each of this can be a string (name of a
        built-in function), function or a `keras.metrics.Metric`
        instance. See `keras.metrics`. Typically you will use
        `metrics=['accuracy']`. A function is any callable with the
        signature `result = fn(y_true, _pred)`. To specify different
        metrics for different outputs of a multi-output model, you could
        also pass a dictionary, such as
        `metrics={'a':'accuracy', 'b':['accuracy', 'mse']}`.
        You can also pass a list to specify a metric or a list of
        metrics for each output, such as
        `metrics=[['accuracy'], ['accuracy', 'mse']]`
        or `metrics=['accuracy', ['accuracy', 'mse']]`. When you pass
        the strings 'accuracy' or 'acc', we convert this to one of
        `keras.metrics.BinaryAccuracy`,
        `keras.metrics.CategoricalAccuracy`,
        `keras.metrics.SparseCategoricalAccuracy` based on the
        shapes of the targets and of the model output. A similar
        conversion is done for the strings `"crossentropy"`
        and `"ce"` as well.
        The metrics passed here are evaluated without sample weighting;
        if you would like sample weighting to apply, you can specify
        your metrics via the `weighted_metrics` argument instead.
    weighted_metrics: List of metrics to be evaluated and weighted by
        `sample_weight` or `class_weight` during training and testing.
    run_eagerly: Bool. If `True`, this model's forward pass
         will never be compiled. It is recommended to leave this
         as `False` when training (for best performance),
         and to set it to `True` when debugging.
    steps_per_execution: Int. The number of batches to run
        during each a single compiled function call. Running multiple
        batches inside a single compiled function call can
        greatly improve performance on TPUs or small models with a large
        Python overhead. At most, one full epoch will be run each
        execution. If a number larger than the size of the epoch is
        passed, the execution will be truncated to the size of the
        epoch. Note that if `steps_per_execution` is set to `N`,
        `Callback.on_batch_begin` and `Callback.on_batch_end` methods
        will only be called every `N` batches (i.e. before/after
        each compiled function execution).
        Not supported with the PyTorch backend.
    jit_compile: Bool or `"auto"`. Whether to use XLA compilation when
        compiling a model. For `jax` and `tensorflow` backends,
        `jit_compile="auto"` enables XLA compilation if the model
        supports it, and disabled otherwise.
        For `torch` backend, `"auto"` will default to eager
        execution and `jit_compile=True` will run with `torch.compile`
        with the `"inductor"` backend.
    auto_scale_loss: Bool. If `True` and the model dtype policy is
        `"mixed_float16"`, the passed optimizer will be automatically
        wrapped in a `LossScaleOptimizer`, which will dynamically
        scale the loss to prevent underflow.

Note:
    Trainable variables are determined at `compile()` time. If you
    modify the `trainable` property of a layer after calling
    `compile()`, those changes will not take effect during `fit()`
    unless `compile()` is called again.

    Recommended workflow when changing trainable variables:
    ```python
    # Initial training with some layers
    model.compile(optimizer="adam", loss="mse")
    model.fit(x_train, y_train)

    # Change trainable flags
    layer.trainable = False  # or True

    # Recompile for the change to take effect
    model.compile(optimizer="adam", loss="mse")
    model.fit(x_train, y_train)
    ```

    This behavior applies to all Keras backends and is also documented
    in the transfer learning guide.
File:      c:\users\sneha\anaconda3\lib\site-packages\keras\src\trainers\trainer.py
Type:      method

In [57]:
import warnings
warnings.filterwarnings('ignore')

In [59]:
from scikeras.wrappers import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
import optuna
from optuna_integration import OptunaSearchCV

In [40]:
def create_model(n_layers=1):
    model = Sequential()
    model.add(Dense(units=6, activation='relu', input_dim=9)) 
    
    for i in range(n_layers - 1):
        model.add(Dense(units=6, activation='relu'))
        
    model.add(Dense(units=1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [41]:
KerasClassifier?

Init signature:
KerasClassifier(
    model: Union[NoneType, Callable[..., keras.src.models.model.Model], keras.src.models.model.Model] = None,
    *,
    build_fn: Union[NoneType, Callable[..., keras.src.models.model.Model], keras.src.models.model.Model] = None,
    warm_start: bool = False,
    random_state: Union[int, numpy.random.mtrand.RandomState, NoneType] = None,
    optimizer: Union[str, keras.src.optimizers.optimizer.Optimizer, Type[keras.src.optimizers.optimizer.Optimizer]] = 'rmsprop',
    loss: Union[str, keras.src.losses.loss.Loss, Type[keras.src.losses.loss.Loss], Callable, NoneType] = None,
    metrics: Optional[List[Union[str, keras.src.metrics.metric.Metric, Type[keras.src.metrics.metric.Metric], Callable]]] = None,
    batch_size: Optional[int] = None,
    validation_batch_size: Optional[int] = None,
    verbose: int = 1,
    callbacks: Optional[List[Union[keras.src.callbacks.callback.Callback, Type[keras.src.callbacks.callback.Callback]]]] = None,
    validation_split: float = 0.0,
    shuffle: bool = True,
    run_eagerly: bool = False,
    epochs: int = 1,
    class_weight: Union[Dict[Any, float], str, NoneType] = None,
    **kwargs,
)
Docstring:
Implementation of the scikit-learn classifier API for Keras.

Below are a list of SciKeras specific parameters. For details on other parameters,
please see the see the `keras.Model documentation <https://www.tensorflow.org/api_docs/python/tf/keras/Model>`_.

Parameters
----------
model : Union[None, Callable[..., keras.Model], keras.Model], default None
    Used to build the Keras Model. When called,
    must return a compiled instance of a Keras Model
    to be used by `fit`, `predict`, etc.
    If None, you must implement ``_keras_build_fn``.
optimizer : Union[str, keras.optimizers.Optimizer, Type[keras.optimizers.Optimizer]], default "rmsprop"
    This can be a string for Keras' built in optimizers,
    an instance of keras.optimizers.Optimizer
    or a class inheriting from keras.optimizers.Optimizer.
    Only strings and classes support parameter routing.
loss : Union[Union[str, keras.losses.Loss, Type[keras.losses.Loss], Callable], None], default None
    The loss function to use for training.
    This can be a string for Keras' built in losses,
    an instance of keras.losses.Loss
    or a class inheriting from keras.losses.Loss .
    Only strings and classes support parameter routing.
random_state : Union[int, np.random.RandomState, None], default None
    Set the Tensorflow random number generators to a
    reproducible deterministic state using this seed.
    Pass an int for reproducible results across multiple
    function calls.
warm_start : bool, default False
    If True, subsequent calls to fit will _not_ reset
    the model parameters but *will* reset the epoch to zero.
    If False, subsequent fit calls will reset the entire model.
    This has no impact on partial_fit, which always trains
    for a single epoch starting from the current epoch.
batch_size : Union[int, None], default None
    Number of samples per gradient update.
    This will be applied to both `fit` and `predict`. To specify different numbers,
    pass `fit__batch_size=32` and `predict__batch_size=1000` (for example).
    To auto-adjust the batch size to use all samples, pass `batch_size=-1`.
class_weight : Union[Dict[Any, float], str, None], default None
    Weights associated with classes in the form ``{class_label: weight}``.
    If not given, all classes are supposed to have weight one.
    The "balanced" mode uses the values of y to automatically adjust
    weights inversely proportional to class frequencies in the input data
    as ``n_samples / (n_classes * np.bincount(y))``.
    Note that these weights will be multiplied with sample_weight (passed
    through the fit method) if sample_weight is specified.

Attributes
----------
model_ : keras.Model
    The instantiated and compiled Keras Model. For pre-built models, this
    will just be a reference to the passed Model instance.
history_ : Dict[str, List[Any]]
    Dictionary of the format ``{metric_str_name: [epoch_0_data, epoch_1_data, ..., epoch_n_data]}``.
initialized_ : bool
    True if this estimator has been initialized (i.e. predict can be called upon it).
    Note that this does not guarantee that the model is "fitted": if ``BaseWrapper.initialize``
    was called instead of fit the model wil likely have random weights.
target_encoder_ : sklearn-transformer
    Transformer used to pre/post process the target y.
feature_encoder_ : sklearn-transformer
    Transformer used to pre/post process the features/input X.
n_outputs_expected_ : int
    The number of outputs the Keras Model is expected to have, as determined by ``target_transformer_``.
target_type_ : str
    One of:

    * 'continuous': y is an array-like of floats that are not all
      integers, and is 1d or a column vector.
    * 'continuous-multioutput': y is a 2d array of floats that are
      not all integers, and both dimensions are of size > 1.
    * 'binary': y contains <= 2 discrete values and is 1d or a column
      vector.
    * 'multiclass': y contains more than two discrete values, is not a
      sequence of sequences, and is 1d or a column vector.
    * 'multiclass-multioutput': y is a 2d array that contains more
      than two discrete values, is not a sequence of sequences, and both
      dimensions are of size > 1.
    * 'multilabel-indicator': y is a label indicator matrix, an array
      of two dimensions with at least two columns, and at most 2 unique
      values.
    * 'unknown': y is array-like but none of the above, such as a 3d
      array, sequence of sequences, or an array of non-sequence objects.
y_shape_ : Tuple[int]
    Shape of the target y that the estimator was fitted on.
y_dtype_ : np.dtype
    Dtype of the target y that the estimator was fitted on.
X_shape_ : Tuple[int]
    Shape of the input X that the estimator was fitted on.
X_dtype_ : np.dtype
    Dtype of the input X that the estimator was fitted on.
n_features_in_ : int
    The number of features seen during `fit`.
n_outputs_ : int
    Dimensions of y that the transformer was trained on.
n_outputs_expected_ : int
    Number of outputs the Keras Model is expected to have.
classes_ : Iterable
    The classes seen during `fit`.
n_classes_ : int
    The number of classes seen during `fit`.
File:           c:\users\sneha\anaconda3\lib\site-packages\scikeras\wrappers.py
Type:           type
Subclasses:

In [42]:
wrapped_classifier = KerasClassifier(model=create_model, n_layers=1, verbose=0)

In [43]:
param_distributions = {
    "model__n_layers": optuna.distributions.IntDistribution(1, 3),
    "optimizer__learning_rate": optuna.distributions.FloatDistribution(1e-5, 1e-1, log=True)
}

In [44]:
OptunaSearchCV?

Init signature:
OptunaSearchCV(
    estimator: "'sklearn.base.BaseEstimator'",
    param_distributions: 'Mapping[str, distributions.BaseDistribution]',
    *,
    cv: "int | 'BaseCrossValidator' | Iterable | None" = None,
    enable_pruning: 'bool' = False,
    error_score: 'Number | float | str' = nan,
    max_iter: 'int' = 1000,
    n_jobs: 'int | None' = None,
    n_trials: 'int | None' = 10,
    random_state: 'int | np.random.RandomState | None' = None,
    refit: 'bool' = True,
    return_train_score: 'bool' = False,
    scoring: 'Callable[..., float] | str | None' = None,
    study: 'study_module.Study | None' = None,
    subsample: 'float | int' = 1.0,
    timeout: 'float | None' = None,
    verbose: 'int' = 0,
    callbacks: 'list[Callable[[study_module.Study, FrozenTrial], None]] | None' = None,
    catch: 'Iterable[type[Exception]] | type[Exception]' = (),
) -> 'None'
Docstring:
Hyperparameter search with cross-validation.

Args:
    estimator:
        Object to use to fit the data. This is assumed to implement the
        scikit-learn estimator interface. Either this needs to provide
        ``score``, or ``scoring`` must be passed.

    param_distributions:
        Dictionary where keys are parameters and values are distributions.
        Distributions are assumed to implement the optuna distribution
        interface.

    cv:
        Cross-validation strategy. Possible inputs for cv are:

        - :obj:`None`, to use the default 5-fold cross validation,
        - integer to specify the number of folds in a CV splitter,
        - `CV splitter <https://scikit-learn.org/stable/glossary.html#term-CV-splitter>`_,
        - an iterable yielding (train, validation) splits as arrays of indices.

        For integer, if ``estimator`` is a classifier and ``y`` is
        either binary or multiclass,
        :class:`sklearn.model_selection.StratifiedKFold` is used. otherwise,
        :class:`sklearn.model_selection.KFold` is used.

    enable_pruning:
        If :obj:`True`, pruning is performed in the case where the
        underlying estimator supports ``partial_fit``.

    error_score:
        Value to assign to the score if an error occurs in fitting. If
        ``"raise"``, the error is raised. If numeric,
        :class:`sklearn.exceptions.FitFailedWarning` is raised. This does not
        affect the refit step, which will always raise the error.

    max_iter:
        Maximum number of epochs. This is only used if the underlying
        estimator supports ``partial_fit``.

    n_jobs:
        Number of :obj:`threading` based parallel jobs. :obj:`None` means ``1``.
        ``-1`` means using the number is set to CPU count.

            .. note::
                ``n_jobs`` allows parallelization using :obj:`threading` and may suffer from
                `Python's GIL <https://wiki.python.org/moin/GlobalInterpreterLock>`_.
                It is recommended to use `process-based optimization <https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#distributed>`_
                if ``func`` is CPU bound.

    n_trials:
        Number of trials. If :obj:`None`, there is no limitation on the
        number of trials. If ``timeout`` is also set to :obj:`None`,
        the study continues to create trials until it receives a
        termination signal such as Ctrl+C or SIGTERM. This trades off
        runtime vs quality of the solution.

    random_state:
        Seed of the pseudo random number generator. If int, this is the
        seed used by the random number generator. If
        :class:`numpy.random.RandomState` object, this is the random number
        generator. If :obj:`None`, the global random state from
        :mod:`numpy.random` is used.

    refit:
        If :obj:`True`, refit the estimator with the best found
        hyperparameters. The refitted estimator is made available at the
        ``best_estimator_`` attribute and permits using ``predict``
        directly.

    return_train_score:
        If :obj:`True`, training scores will be included. Computing
        training scores is used to get insights on how different
        hyperparameter settings impact the overfitting/underfitting
        trade-off. However computing training scores can be
        computationally expensive and is not strictly required to select
        the hyperparameters that yield the best generalization
        performance.

    scoring:
        String or callable to evaluate the predictions on the validation data.
        If :obj:`None`, ``score`` on the estimator is used.

    study:
        Study corresponds to the optimization task. If :obj:`None`, a new
        study is created.

    subsample:
        Proportion of samples that are used during hyperparameter search.

        - If int, then draw ``subsample`` samples.
        - If float, then draw ``subsample`` * ``X.shape[0]`` samples.

    timeout:
        Time limit in seconds for the search of appropriate models. If
        :obj:`None`, the study is executed without time limitation. If
        ``n_trials`` is also set to :obj:`None`, the study continues to
        create trials until it receives a termination signal such as
        Ctrl+C or SIGTERM. This trades off runtime vs quality of the
        solution.

    verbose:
        Verbosity level. The higher, the more messages.

    callbacks:
        List of callback functions that are invoked at the end of each trial. Each function
        must accept two parameters with the following types in this order:
        :class:`~optuna.study.Study` and :class:`~optuna.trial.FrozenTrial`.

        .. seealso::

            See the tutorial of `Callback for Study.optimize <https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/007_optuna_callback.html#optuna-callback>`_
            for how to use and implement callback functions.

    catch:
        A study continues to run even when a trial raises one of the exceptions specified
        in this argument. Default is an empty tuple, i.e. the study will stop for any
        exception except for :class:`~optuna.exceptions.TrialPruned`.

Attributes:
    best_estimator_:
        Estimator that was chosen by the search. This is present only if
        ``refit`` is set to :obj:`True`.

    n_splits_:
        Number of cross-validation splits.

    refit_time_:
        Time for refitting the best estimator. This is present only if
        ``refit`` is set to :obj:`True`.

    sample_indices_:
        Indices of samples that are used during hyperparameter search.

    scorer_:
        Scorer function.

    study_:
        Actual study.

Examples:

.. note::
    By following the scikit-learn convention for scorers, the direction of optimization is
    ``maximize``. See https://scikit-learn.org/stable/modules/model_evaluation.html.
    For the minimization problem, please multiply ``-1``.

.. note::
    Added in v0.17.0 as an experimental feature. The interface may change in newer versions
    without prior notice. See https://github.com/optuna/optuna/releases/tag/v0.17.0.
File:           c:\users\sneha\anaconda3\lib\site-packages\optuna_integration\sklearn\sklearn.py
Type:           type
Subclasses:

In [45]:
optuna_search = OptunaSearchCV(
    estimator=wrapped_classifier, 
    param_distributions=param_distributions, 
    n_trials=5, 
    cv=3,
    error_score='raise'
)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14264\379159384.py:1: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  optuna_search = OptunaSearchCV(

In [ ]:
optuna_search.fit(X_train, y_train)

[I 2026-06-04 16:09:33,100] A new study created in memory with name: no-name-4c4b31b4-4e34-44c8-9dfa-7b1f92a7d4b0
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-06-04 16:09:41,334] Trial 0 finished with value: 0.7954982746436516 and parameters: {'model__n_layers': 3, 'optimizer__learning_rate': 1.918216456511338e-05}. Best is trial 0 with value: 0.7954982746436516.
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-06-04 16:09:49,682] Trial 1 finished with value: 0.833243603364283 and parameters: {'model__n_layers': 3, 'optimizer__learning_rate': 0.0347766809885771}. Best is trial 1 with value: 0.833243603364283.
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-06-04 16:09:57,632] Trial 2 finished with value: 0.89686871474149 and parameters: {'model__n_layers': 2, 'optimizer__learning_rate': 0.019131213207333596}. Best is trial 2 with value: 0.89686871474149.
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [91]:
optuna_search.best_params_

{'model__n_layers': 3, 'optimizer__learning_rate': 0.001002824063808306}

In [92]:
optuna_search.best_score_

0.8503681507178444

In [93]:
best_model = optuna_search.best_estimator_

In [94]:
y_pred_test_cv = best_model.predict(X_test)
y_pred_test_cv_optimized = (y_pred_test_cv > 0.5)

In [95]:
y_pred_train_cv = best_model.predict(X_train)
y_pred_train_cv_optimized = (y_pred_train_cv > 0.5)

In [96]:
print(classification_report(y_train, y_pred_train_cv_optimized))
print(classification_report(y_test, y_pred_test_cv_optimized))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      6388
           1       0.00      0.00      0.00      1612

    accuracy                           0.80      8000
   macro avg       0.40      0.50      0.44      8000
weighted avg       0.64      0.80      0.71      8000

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1575
           1       0.00      0.00      0.00       425

    accuracy                           0.79      2000
   macro avg       0.39      0.50      0.44      2000
weighted avg       0.62      0.79      0.69      2000

In [128]:
# End of the Notebook